# Generated by Django 3.2.4 on 2021-06-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID categoría')),
                ('nombreCategoria', models.CharField(max_length=80, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('idResidente', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut sin puntos')),
                ('nombreResidente', models.CharField(max_length=100, verbose_name='Nombre Completo del Residente')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('nombreFamiliar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de familiar a cargo')),
                ('imagenCarnet', models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Foto carnet')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apoyo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('marca', models.CharField(max_length=40, verbose_name='Marca Producto')),
                ('nombreProducto', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('precio', models.IntegerField(verbose_name='Precio Unitario')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock')),
                ('imagen', models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apoyo.categoria')),
            ],
        ),
    ]
