# Generated by Django 3.2.4 on 2021-06-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apoyo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residente',
            name='categoria',
        ),
    ]
